apiVersion: v1
kind: Pod
metadata:
  name: webapp
spec:
  containers:
  - name: webapp
    image: hossambarakat/k8s-security-webapp
    imagePullPolicy: Always
    ports:
        - containerPort: 3000
    securityContext:
      privileged: true
    volumeMounts:
      - name: sec-vol
        mountPath: "/sec-vol"
  volumes:
    - name: sec-vol
      emptyDir: {}