apiVersion: v1
kind: Pod
metadata:
  name: webapp
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 2000
    fsGroup: 3000
  containers:
  - name: webapp
    image: hossambarakat/k8s-security-webapp
    ports:
      - containerPort: 3000
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
