apiVersion: v1
kind: Pod
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  # Opt out of automounting API credentials for a particular pod
  serviceAccount: webapp-service-account
  # Opt out of automounting API credentials for a service account
  # automountServiceAccountToken: false
  containers:
  - name: webapp
    image: hossambarakat/k8s-security-webapp
