apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  # Opt out of automounting API credentials for a particular pod
  # serviceAccount: nginx-service-account
  # Opt out of automounting API credentials for a service account
  # automountServiceAccountToken: false
  containers:
  - name: nginx
    image: nginx
