kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: my-role
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch"]
  # - apiGroups: [""]
  #   resources: ["serviceaccount"]
  #   verbs: ["get", "list"]