apiVersion: v1
kind: Pod
metadata:
  name: webapp-with-hostroot
spec:
  containers:
  - name: webapp-with-rootpath
    image: hossambarakat/k8s-security-webapp
    securityContext:
      privileged: true
    volumeMounts:
        - name: host-root
          mountPath: "/hostroot"
  volumes:
  - name: host-root
    hostPath:
      path: /