apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
  annotations:
    #
    # container.apparmor.security.beta.kubernetes.io/nginx: runtime/default
    #
    container.seccomp.security.alpha.kubernetes.io/nginx: docker/default
spec:
  containers:
  - name: nginx
    image: nginx


# Reference https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/aks/operator-best-practices-cluster-security.md